[package]
name = "igat-dll"
version = "0.1.0"
edition = "2021"

[lib]
name = "igat"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
igat = { version = "0.0.4" path = "../igat" }